version: '3.8'

services:

  mongodb:
    container_name: "mongodb"
    hostname: "mongodb"
    image: mongo:5.0.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.db:/data/db
      - ./.configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  node:
    container_name: "node"
    hostname: "node"
    image: node:17.3.0
    tty: true
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./node_src:/src
    working_dir: "/src"
